x = np.linspace(0.0, 2.0 * np.pi, 300)
figure, axis = plt.subplots(layout="constrained")
axis.plot(x, np.sin(x), label="sin(x)")
axis.plot(x, np.cos(x), label="cos(x)")
axis.set_xlabel("x")
axis.set_ylabel("amplitude")
axis.set_title("Writer-resolved Python / Matplotlib plot")
axis.grid(alpha=0.25)
axis.legend()
